[package]
name = "clack-extensions"
version = "0.1.0"
edition = "2021"
rust-version = "1.72.0"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clack-plugin = { workspace = true, optional = true }
clack-host = { workspace = true, optional = true, default-features = false }
clack-common = { workspace = true }
clap-sys = { workspace = true }

bitflags = { workspace = true }
raw-window-handle_05 = { workspace = true, optional = true }
raw-window-handle_06 = { workspace = true, optional = true }

[features]
all-extensions = [
    "ambisonic",
    "audio-ports",
    "audio-ports-activation",
    "audio-ports-config",
    "configurable-audio-ports",
    "context-menu",
    "event-registry",
    "gui",
    "latency",
    "log",
    "note-name",
    "note-ports",
    "params",
    "param-indication",
    "posix-fd",
    "preset-load",
    "remote-controls",
    "render",
    "state",
    "state-context",
    "surround",
    "tail",
    "thread-check",
    "thread-pool",
    "timer",
    "track-info",
    "voice-info"
]
ambisonic = []
audio-ports = []
audio-ports-activation = []
audio-ports-config = []
configurable-audio-ports = []
context-menu = []
event-registry = []
gui = []
latency = []
log = []
note-name = []
note-ports = []
params = []
param-indication = []
posix-fd = []
preset-load = []
remote-controls = []
render = []
state = []
# If a plugin implements state-context, it must also implement state
state-context = ["state"]
surround = []
tail = []
thread-check = []
thread-pool = []
timer = []
track-info = []
voice-info = []
